### ISSUE TITLE
FOD doesn't work on yaap when aod enabled

### ISSUE THREAD

**Issue by WewillChen** [atndko/Neptune_kernel_sm8150_oneplus#3]
V105 with yaap 0624, FOD doesn't work on AOD

**Comment by atndko** [comment]
Try to remove L59 to L64 in anykernel.sh and flash again?

**Comment by WewillChen** [comment]
> Try to remove L59 to L64 in anykernel.sh and flash again?

Totally dead after deleting L59 to L64

**Comment by atndko** [comment]
Then just don't use my kernel :)
