### ISSUE TITLE
Fingerprint not working on lock screen.  HD1905 w/ Project-Xtended

### ISSUE THREAD

**Issue by HippieMitch** [atndko/Neptune_kernel_sm8150_oneplus#5]
My fingerprint isn't being read on the lock screen in Project-Xtended on my OnePlus 7T.  It works from the Ambient display and in apps.  It appears to be intermittent.  I don't have this issue with other kernels on the same ROM.  Also, new to android troubleshooting, usually Linux kernel stuff.  I don't have a logcat for the event, but I could probably figure out how to get one if necessary.  My model is an HD1905.  Great work everybody btw, this kernel is really amazing.

**Comment by atndko** [comment]
I don't care custom ROMs

**Comment by HippieMitch** [comment]
There may have been a warning about a custom ROM lol.  No worries, thanks.
