### ISSUE TITLE
It seems battery capacity learning not work on Android 11 kernel

### ISSUE THREAD

**Issue by akw28888** [atndko/Neptune_kernel_sm8150_oneplus#6]
Hi,

On the Android 11 kernel, it seems the battery capacity learning is not working.

The /sys/class/power_supply/bms/charge_full_design node always return 3588000.
And the /sys/class/power_supply/bms/charge_full node usually return 0.

And I found sometimes the battery is overdischarge, the bat voltage only 3.2-3.4V, and the power will suddenly cutoff, then the phone shutdown.
 
But on Android 10 kernel, the charge_full node will be update when the battery charge full, and no overdischarge issue on it.

**Comment by akw28888** [comment]
bms/uevent output (on charging)
/sys/class/power_supply/bms/uevent:                                               POWER_SUPPLY_NAME=bms                                                                   POWER_SUPPLY_CAPACITY=48                                                                POWER_SUPPLY_REAL_CAPACITY=0                                                            POWER_SUPPLY_CAPACITY_RAW=0                                                             POWER_SUPPLY_CC_SOC=-1440                                                               POWER_SUPPLY_TEMP=405                                                                   POWER_SUPPLY_VOLTAGE_NOW=4020000                                                        POWER_SUPPLY_VOLTAGE_OCV=2978031                                                        POWER_SUPPLY_VOLTAGE_AVG=4057992                                                        POWER_SUPPLY_CURRENT_NOW=-2621000                                                       POWER_SUPPLY_CURRENT_AVG=854533                                                         POWER_SUPPLY_RESISTANCE_ID=200000                                                       POWER_SUPPLY_RESISTANCE=298828                                                          POWER_SUPPLY_ESR_ACTUAL=-22                                                             POWER_SUPPLY_ESR_NOMINAL=-22                                                            POWER_SUPPLY_BATTERY_TYPE=OP_4000mAh                                                    POWER_SUPPLY_CHARGE_FULL_DESIGN=3588000                                                 POWER_SUPPLY_VOLTAGE_MAX_DESIGN=4370000                                                 POWER_SUPPLY_CHARGE_NOW_RAW=-516747                                                     POWER_SUPPLY_CHARGE_NOW=0                                                               POWER_SUPPLY_CHARGE_FULL=0                                                              POWER_SUPPLY_CHARGE_COUNTER=-220817                                                     POWER_SUPPLY_CHARGE_COUNTER_SHADOW=0                                                    POWER_SUPPLY_CYCLE_COUNTS=15 16 14 12 8 8 5 4                                           POWER_SUPPLY_SOC_REPORTING_READY=1                                                      POWER_SUPPLY_CLEAR_SOH=0                                                                POWER_SUPPLY_SOH=51                                                                     POWER_SUPPLY_DEBUG_BATTERY=0                                                            POWER_SUPPLY_CONSTANT_CHARGE_VOLTAGE=4339850                                            POWER_SUPPLY_TIME_TO_FULL_AVG=60811                                                     POWER_SUPPLY_TIME_TO_EMPTY_AVG=-1                                                       POWER_SUPPLY_CC_STEP=0                                                                  POWER_SUPPLY_CC_STEP_SEL=0                                                              POWER_SUPPLY_BATT_AGE_LEVEL=-22                                                         POWER_SUPPLY_POWER_NOW=-1651051                                                         POWER_SUPPLY_POWER_AVG=-554679                                                          POWER_SUPPLY_SCALE_MODE_EN=0                                                            POWER_SUPPLY_CALIBRATE=-22                                                              POWER_SUPPLY_BQ_SOC=48                                                                  POWER_SUPPLY_BATTERY_HEALTH=100                                                         POWER_SUPPLY_REMAINING_CAPACITY=0

The CHARGE_COUNTER value is decrease when charging, but it should increase when charging. also the REAL_CAPACITY always return 0.

**Comment by atndko** [comment]
I never said it's supposed on Android 11
