### ISSUE TITLE
issue with cmpxchg.h

### ISSUE THREAD

**Issue by kimocoder** [atndko/Neptune_kernel_sm8150_oneplus#7]
In file included from /root/Neptune_kernel_sm8150_oneplus/kernel/bounds.c:10:
In file included from /root/Neptune_kernel_sm8150_oneplus/include/linux/page-flags.h:10:
In file included from /root/Neptune_kernel_sm8150_oneplus/include/linux/bug.h:5:
In file included from /root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/bug.h:37:
In file included from /root/Neptune_kernel_sm8150_oneplus/include/asm-generic/bug.h:16:
In file included from /root/Neptune_kernel_sm8150_oneplus/include/linux/kernel.h:11:
In file included from /root/Neptune_kernel_sm8150_oneplus/include/linux/bitops.h:21:
In file included from /root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/bitops.h:37:
In file included from /root/Neptune_kernel_sm8150_oneplus/include/asm-generic/bitops/atomic.h:5:
In file included from /root/Neptune_kernel_sm8150_oneplus/include/linux/atomic.h:7:
In file included from /root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/atomic.h:41:
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:50:1: error: expected string literal in 'asm'
__XCHG_CASE(w, b,     ,  8,        ,  ,  ,  ,         )
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \
                     ^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:51:1: error: expected string literal in 'asm'                   
__XCHG_CASE(w, h,     , 16,        ,  ,  ,  ,         )
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \
                     ^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:52:1: error: expected string literal in 'asm'                   
__XCHG_CASE(w,  ,     , 32,        ,  ,  ,  ,         )
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \
                     ^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:53:1: error: expected string literal in 'asm'                   
__XCHG_CASE( ,  ,     , 64,        ,  ,  ,  ,         )
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \
                     ^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:54:1: error: expected string literal in 'asm'                   
__XCHG_CASE(w, b, acq_,  8,        , a, a,  , "memory")
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \
                     ^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:55:1: error: expected string literal in 'asm'                   
__XCHG_CASE(w, h, acq_, 16,        , a, a,  , "memory")
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \
                     ^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:56:1: error: expected string literal in 'asm'                   
__XCHG_CASE(w,  , acq_, 32,        , a, a,  , "memory")
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \
                     ^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:57:1: error: expected string literal in 'asm'                   
__XCHG_CASE( ,  , acq_, 64,        , a, a,  , "memory")
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \
                     ^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:58:1: error: expected string literal in 'asm'                   
__XCHG_CASE(w, b, rel_,  8,        ,  ,  , l, "memory")
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \
                     ^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:59:1: error: expected string literal in 'asm'                   
__XCHG_CASE(w, h, rel_, 16,        ,  ,  , l, "memory")
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \
                     ^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:60:1: error: expected string literal in 'asm'                   
__XCHG_CASE(w,  , rel_, 32,        ,  ,  , l, "memory")
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \
                     ^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:61:1: error: expected string literal in 'asm'                   
__XCHG_CASE( ,  , rel_, 64,        ,  ,  , l, "memory")
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \
                     ^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:62:1: error: expected string literal in 'asm'                   
__XCHG_CASE(w, b,  mb_,  8, dmb ish,  , a, l, "memory")
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \
                     ^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:63:1: error: expected string literal in 'asm'                   
__XCHG_CASE(w, h,  mb_, 16, dmb ish,  , a, l, "memory")
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \
                     ^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:64:1: error: expected string literal in 'asm'                   
__XCHG_CASE(w,  ,  mb_, 32, dmb ish,  , a, l, "memory")
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \
                     ^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:65:1: error: expected string literal in 'asm'                   
__XCHG_CASE( ,  ,  mb_, 64, dmb ish,  , a, l, "memory")
^
/root/Neptune_kernel_sm8150_oneplus/arch/arm64/include/asm/cmpxchg.h:38:15: note: expanded from macro '__XCHG_CASE'                  
        asm volatile(ARM64_LSE_ATOMIC_INSN(                                     \

**Comment by atndko** [comment]
never seen these
