### ISSUE TITLE
Fingerprint doesn't do anything 

### ISSUE THREAD

**Issue by Biasio** [atndko/Neptune_kernel_sm8150_oneplus#8]
Hi, 
when pressing the fingerprint sensor it lights up but then it doesn't vibrate or recognize my finger, also it doesn't say "not recognized".
With stock kernel it was working fine.
I'm on Aosp Xtended Android 11 which has sdcardfs dropped, on Oneplus7 (guacamoleb).
Let me know if you need some types of logs!

**Comment by atndko** [comment]
Will fix some days later
